### ISSUE TITLE
[musecoco] I'm still unable to download the checkpoint file.

### ISSUE THREAD

**Issue by heury** [microsoft/muzic#148]
My previous issue has been closed as resolved. 
But I can't download it.
The permission request input window is still displayed, and clicking the request button only shows blank white window.
Would you check the file permission?

**Comment by kyuBin422** [comment]
same as me, they forget to make this link as public access

**Comment by xxupiano** [comment]
Fixed.

**Comment by dramaticmeow** [comment]
Same problem with Musicbert and Telemelody🥺

**Comment by heury** [comment]
Thanks for fixing it.

**Comment by kyuBin422** [comment]
@heury Hey folk, Can you access the checkpoint file? I still cannot.
